### ISSUE TITLE
[QUESTION] does a `kangaroo-headless` exist?

### ISSUE THREAD

**Issue by DrewMcArthur** [holochain/kangaroo-electron#15]
i.e. basically this library, minus the UI parts.  Just an executable that spins up the conductor + a happ, then the admin/app websocket ports are open.  Does that exist somewhere, or not yet?

@matthme thanks for the work you're doing writing this, it's super helpful 😄

**Comment by matthme** [comment]
There is the holochain-runner which seems to have an [0.4 branch](https://github.com/lightningrodlabs/holochain-runner/tree/hc-0.4-rc) but it's probably not as well maintained as the kangaroo. But it might give you some inspiration at least.

And then also I think it wouldn't be too hard to build something like that by re-using the nodejs code of kangaroo, in particular the [holochainManager](https://github.com/holochain/kangaroo-electron/blob/main/src/main/holochainManager.ts) code.

**Comment by DrewMcArthur** [comment]
sweet, thank you for the links!! much appreciated.
